platform :ios, '8.0'
source 'https://github.com/vkovtash/PrivateSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'


target 'VKMessagesViewControllerTest' do
    pod 'ZIMMessagesViewController', :path => '../'
end
